### ISSUE TITLE
Modify PII Module to Include Driver's Licenses

### ISSUE THREAD

**Issue by stewartl97** [cisagov/pe-reports#128]
# 💡 Summary #

The PII filter module needs to filter out drivers licenses as well as other items.

## Motivation and context ##
This will improve our ability to remove personal data.

## Implementation notes ##

Please provide details for implementation, such as:

- Drivers license filtering for all states

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Filter for states with just numbers
- [ ] Filter for states with a combination of letters and numbers up to 9 chars
- [ ] Filter for states using RealID

**Comment by stewartl97** [comment]
@DJensen94 can you provide an update to this issue. I believe it has been completed.

**Comment by DJensen94** [comment]
This was working fine but on a recent run the redact script started failing on the Drivers License Detector, I have broken it out into individual detectors for each state and removed those causing it to fail. I'm going to run through the failures to see what the issue is and see if they can be added back successfully, to ensure we have maximum DL coverage

**Comment by DJensen94** [comment]
Needed to implement with different regex library and make slight adjustments to the regex, but this is all completed now and pushed in the following PR: https://github.com/cisagov/crossfeed/pull/1442
